import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ContainerHeader from '@components/Templates/header/index';
import "./globals.css";
import clsx from 'clsx';
import { ReduxProvider } from "@providers/redux-provider";
import PopUpNotifications from "@/app/components/Molecule/PopUpNotification/index";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          'bg-[#FFFFFF]',
          inter.className
        )}>
        <ReduxProvider>
          <ContainerHeader />
          {children}
          <PopUpNotifications />
        </ReduxProvider>
      </body>
    </html>
  );
}
