import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ContainerHeader from '@components/template/header/index';
import "./globals.css";
import clsx from 'clsx';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          'bg-[#DADADA]',
          inter.className
        )}>
        <ContainerHeader />
        {children}
      </body>
    </html>
  );
}
